[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m

build_flags = -DUSE_TINYUSB

board_build.arduino.earlephilhower.usb_manufacturer = piPiMouse
board_build.arduino.earlephilhower.usb_product = Pico HID Mouse

monitor_speed = 115200